[build]
builder = "nixpacks"
buildCommand = "chmod +x start.sh"

[deploy]
restartPolicyType = "always"
restartPolicyMaxRetries = 10
startCommand = "bash start.sh"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 60
